import { Match, GroupStanding, Team, BroadcastChannel } from "./types";

// Let's define the Teams
export const TEAMS: Record<string, Team> = {
  ARG: { id: "ARG", name: "Argentina", flagCode: "🇦🇷", color: "#74ACDF" },
  FRA: { id: "FRA", name: "France", flagCode: "🇫🇷", color: "#002395" },
  BRA: { id: "BRA", name: "Brazil", flagCode: "🇧🇷", color: "#009739" },
  GER: { id: "GER", name: "Germany", flagCode: "🇩🇪", color: "#000000" },
  JPN: { id: "JPN", name: "Japan", flagCode: "🇯🇵", color: "#BC002D" },
  ESP: { id: "ESP", name: "Spain", flagCode: "🇪🇸", color: "#C60B1E" },
  ENG: { id: "ENG", name: "England", flagCode: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#E00000" },
  CRO: { id: "CRO", name: "Croatia", flagCode: "🇭🇷", color: "#FF0000" },
  MAR: { id: "MAR", name: "Morocco", flagCode: "🇲🇦", color: "#C1272D" },
  POR: { id: "POR", name: "Portugal", flagCode: "🇵🇹", color: "#046A38" },
  USA: { id: "USA", name: "USA", flagCode: "🇺🇸", color: "#0A254C" },
  MEX: { id: "MEX", name: "Mexico", flagCode: "🇲🇽", color: "#006341" },
  CAN: { id: "CAN", name: "Canada", flagCode: "🇨🇦", color: "#DA291C" },
  NED: { id: "NED", name: "Netherlands", flagCode: "🇳🇱", color: "#E45E05" },
  ITA: { id: "ITA", name: "Italy", flagCode: "🇮🇹", color: "#0054A6" },
  SEN: { id: "SEN", name: "Senegal", flagCode: "🇸🇳", color: "#00853F" },
  COL: { id: "COL", name: "Colombia", flagCode: "🇨🇴", color: "#FCD116" },
  RSA: { id: "RSA", name: "South Africa", flagCode: "🇿🇦", color: "#007C5F" },
  KOR: { id: "KOR", name: "South Korea", flagCode: "🇰🇷", color: "#C11B17" },
  CZE: { id: "CZE", name: "Czech Republic", flagCode: "🇨🇿", color: "#113C7A" },
  BIH: {
    id: "BIH",
    name: "Bosnia & Herzegovina",
    flagCode: "🇧🇦",
    color: "#002395",
  },
  QAT: { id: "QAT", name: "Qatar", flagCode: "🇶🇦", color: "#8A1538" },
  SUI: { id: "SUI", name: "Switzerland", flagCode: "🇨🇭", color: "#D52B1E" },
  HAI: { id: "HAI", name: "Haiti", flagCode: "🇭🇹", color: "#00209F" },
  SCO: { id: "SCO", name: "Scotland", flagCode: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", color: "#005EB8" },
  PAR: { id: "PAR", name: "Paraguay", flagCode: "🇵🇾", color: "#D52B1E" },
  AUS: { id: "AUS", name: "Australia", flagCode: "🇦🇺", color: "#000033" },
  TUR: { id: "TUR", name: "Turkey", flagCode: "🇹🇷", color: "#E30A17" },
  CUW: { id: "CUW", name: "Curaçao", flagCode: "🇨🇼", color: "#002B7F" },
  CIV: { id: "CIV", name: "Ivory Coast", flagCode: "🇨🇮", color: "#F77F00" },
  ECU: { id: "ECU", name: "Ecuador", flagCode: "🇪🇨", color: "#FFDD00" },
  SWE: { id: "SWE", name: "Sweden", flagCode: "🇸🇪", color: "#006AA7" },
  TUN: { id: "TUN", name: "Tunisia", flagCode: "🇹🇳", color: "#E10613" },
  BEL: { id: "BEL", name: "Belgium", flagCode: "🇧🇪", color: "#ED2939" },
  EGY: { id: "EGY", name: "Egypt", flagCode: "🇪🇬", color: "#C09307" },
  IRN: { id: "IRN", name: "Iran", flagCode: "🇮🇷", color: "#239E46" },
  NZL: { id: "NZL", name: "New Zealand", flagCode: "🇳🇿", color: "#00247D" },
  CPV: { id: "CPV", name: "Cape Verde", flagCode: "🇨🇻", color: "#003893" },
  KSA: { id: "KSA", name: "Saudi Arabia", flagCode: "🇸🇦", color: "#006C35" },
  URU: { id: "URU", name: "Uruguay", flagCode: "🇺🇾", color: "#43A1D5" },
  REP2: {
    id: "REP2",
    name: "Intercontinental Playoff 2 (BOL/IRQ)",
    flagCode: "🌍",
    color: "#7f8c8d",
  },
  NOR: { id: "NOR", name: "Norway", flagCode: "🇳🇴", color: "#EF2B2D" },
  ALG: { id: "ALG", name: "Algeria", flagCode: "🇩🇿", color: "#006233" },
  AUT: { id: "AUT", name: "Austria", flagCode: "🇦🇹", color: "#ED2939" },
  JOR: { id: "JOR", name: "Jordan", flagCode: "🇯🇴", color: "#C1272D" },
  COD: { id: "COD", name: "DR Congo", flagCode: "🇨🇩", color: "#007FFF" },
  UZB: { id: "UZB", name: "Uzbekistan", flagCode: "🇺🇿", color: "#00BFFF" },
  GHA: { id: "GHA", name: "Ghana", flagCode: "🇬🇭", color: "#FCD116" },
  PAN: { id: "PAN", name: "Panama", flagCode: "🇵🇦", color: "#DA121A" },
};

export const RECENT_BROADCASTS = [
  {
    id: "1",
    name: "Fox Network",
    type: "free",
    logoColor: "#1E3A8A",
    urlPlaceholder: "https://foxsports.com",
  },
  {
    id: "2",
    name: "TV Globo",
    type: "free",
    logoColor: "#DC2626",
    urlPlaceholder: "https://globoplay.globo.com",
  },
  {
    id: "3",
    name: "ESPN+",
    type: "cable",
    logoColor: "#CC0000",
    urlPlaceholder: "https://espn.com",
  },
  {
    id: "4",
    name: "Peacock",
    type: "streaming",
    logoColor: "#000000",
    urlPlaceholder: "https://peacocktv.com",
  },
  {
    id: "5",
    name: "FIFA+ Stream",
    type: "streaming",
    logoColor: "#0EA5E9",
    urlPlaceholder: "https://fifa.com/fifaplus",
  },
] as const;

// Bracket Knockout Stage Matches
// Bracket matches are created after the group stage ends
export const BRACKET_MATCHES: Match[] = [];

export const GROUP_STANDINGS: GroupStanding[] = [
  {
    groupName: "Group A",
    standings: [
      {
        team: TEAMS.MEX,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.KOR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.RSA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.CZE,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group B",
    standings: [
      {
        team: TEAMS.CAN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.SUI,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.BIH,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.QAT,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group C",
    standings: [
      {
        team: TEAMS.BRA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.MAR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.SCO,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.HAI,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group D",
    standings: [
      {
        team: TEAMS.USA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.TUR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.PAR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.AUS,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group E",
    standings: [
      {
        team: TEAMS.GER,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.ECU,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.CIV,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.CUW,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group F",
    standings: [
      {
        team: TEAMS.NED,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.JPN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.SWE,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.TUN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group G",
    standings: [
      {
        team: TEAMS.BEL,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.EGY,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.IRN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.NZL,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group H",
    standings: [
      {
        team: TEAMS.ESP,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.URU,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.KSA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.CPV,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group I",
    standings: [
      {
        team: TEAMS.FRA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.SEN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.NOR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.REP2,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group J",
    standings: [
      {
        team: TEAMS.ARG,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.AUT,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.ALG,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.JOR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group K",
    standings: [
      {
        team: TEAMS.POR,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.COL,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.COD,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.UZB,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
  {
    groupName: "Group L",
    standings: [
      {
        team: TEAMS.ENG,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.CRO,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.GHA,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
      {
        team: TEAMS.PAN,
        played: 0,
        won: 0,
        drawn: 0,
        lost: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
        points: 0,
      },
    ],
  },
];

// Complete official list of 72 simulated Group Stage Matches for World Cup 2026
export const GROUP_MATCHES: Match[] = [
  // --- GRUPO A ---
  {
    id: "gm-1",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.MEX,
    teamB: TEAMS.RSA,
    status: "scheduled",
    datetime: "Jun 11, 2026 - 16:00",
    timestamp: 1781280000000,
    stadium: "Estádio Azteca",
    city: "Mexico City",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-2",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.KOR,
    teamB: TEAMS.CZE,
    status: "scheduled",
    datetime: "Jun 11, 2026 - 23:00",
    timestamp: 1781305200000,
    stadium: "Estádio Akron",
    city: "Guadalajara",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-3",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.CZE,
    teamB: TEAMS.RSA,
    status: "scheduled",
    datetime: "Jun 18, 2026 - 13:00",
    timestamp: 1781874000000,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    broadcasts: [RECENT_BROADCASTS[2], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-4",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.MEX,
    teamB: TEAMS.KOR,
    status: "scheduled",
    datetime: "Jun 18, 2026 - 22:00",
    timestamp: 1781906400000,
    stadium: "Estádio Akron",
    city: "Guadalajara",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-5",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.CZE,
    teamB: TEAMS.MEX,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 22:00",
    timestamp: 1782424800000,
    stadium: "Estádio Azteca",
    city: "Mexico City",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[1]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-6",
    stage: "Group",
    group: "Group A",
    teamA: TEAMS.RSA,
    teamB: TEAMS.KOR,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 22:00",
    timestamp: 1782424800000,
    stadium: "Estádio BBVA",
    city: "Monterrey",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO B ---
  {
    id: "gm-7",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.CAN,
    teamB: TEAMS.BIH, // Mapped "Itália" -> BIH to align with Group B Standings
    status: "scheduled",
    datetime: "Jun 12, 2026 - 16:00",
    timestamp: 1781366400000,
    stadium: "BMO Field",
    city: "Toronto",
    broadcasts: [RECENT_BROADCASTS[2], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-8",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.QAT,
    teamB: TEAMS.SUI,
    status: "scheduled",
    datetime: "Jun 13, 2026 - 16:00",
    timestamp: 1781452800000,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-9",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.SUI,
    teamB: TEAMS.BIH, // Mapped "Itália" -> BIH to align with standings
    status: "scheduled",
    datetime: "Jun 18, 2026 - 16:00",
    timestamp: 1781884800000,
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-10",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.CAN,
    teamB: TEAMS.QAT,
    status: "scheduled",
    datetime: "Jun 18, 2026 - 19:00",
    timestamp: 1781895600000,
    stadium: "BC Place",
    city: "Vancouver",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-11",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.SUI,
    teamB: TEAMS.CAN,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 16:00",
    timestamp: 1782403200000,
    stadium: "BC Place",
    city: "Vancouver",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-12",
    stage: "Group",
    group: "Group B",
    teamA: TEAMS.BIH, // Mapped "Itália" -> BIH
    teamB: TEAMS.QAT,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 16:00",
    timestamp: 1782403200000,
    stadium: "Lumen Field",
    city: "Seattle",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO C ---
  {
    id: "gm-13",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.BRA,
    teamB: TEAMS.MAR,
    status: "scheduled",
    datetime: "Jun 13, 2026 - 19:00",
    timestamp: 1781463600000,
    stadium: "MetLife Stadium",
    city: "New York/New Jersey",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-14",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.HAI,
    teamB: TEAMS.SCO,
    status: "scheduled",
    datetime: "Jun 13, 2026 - 22:00",
    timestamp: 1781474400000,
    stadium: "Gillette Stadium",
    city: "Boston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-15",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.SCO,
    teamB: TEAMS.MAR,
    status: "scheduled",
    datetime: "Jun 19, 2026 - 19:00",
    timestamp: 1781982000000,
    stadium: "Gillette Stadium",
    city: "Boston",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-16",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.BRA,
    teamB: TEAMS.HAI,
    status: "scheduled",
    datetime: "Jun 19, 2026 - 22:00",
    timestamp: 1781992800000,
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-17",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.SCO,
    teamB: TEAMS.BRA,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 19:00",
    timestamp: 1782414000000,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-18",
    stage: "Group",
    group: "Group C",
    teamA: TEAMS.MAR,
    teamB: TEAMS.HAI,
    status: "scheduled",
    datetime: "Jun 24, 2026 - 19:00",
    timestamp: 1782414000000,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO D ---
  {
    id: "gm-19",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.USA,
    teamB: TEAMS.PAR,
    status: "scheduled",
    datetime: "Jun 12, 2026 - 22:00",
    timestamp: 1781388000000,
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-20",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.AUS,
    teamB: TEAMS.TUR,
    status: "scheduled",
    datetime: "Jun 13, 2026 - 01:00",
    timestamp: 1781398800000,
    stadium: "BC Place",
    city: "Vancouver",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-21",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.TUR,
    teamB: TEAMS.PAR,
    status: "scheduled",
    datetime: "Jun 19, 2026 - 01:00",
    timestamp: 1781917200000,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-22",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.USA,
    teamB: TEAMS.AUS,
    status: "scheduled",
    datetime: "Jun 19, 2026 - 16:00",
    timestamp: 1781971200000,
    stadium: "Lumen Field",
    city: "Seattle",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-23",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.TUR,
    teamB: TEAMS.USA,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 23:00",
    timestamp: 1782514800000,
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[1]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-24",
    stage: "Group",
    group: "Group D",
    teamA: TEAMS.PAR,
    teamB: TEAMS.AUS,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 23:00",
    timestamp: 1782514800000,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO E ---
  {
    id: "gm-25",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.GER,
    teamB: TEAMS.CUW,
    status: "scheduled",
    datetime: "Jun 14, 2026 - 14:00",
    timestamp: 1781532000000,
    stadium: "NRG Stadium",
    city: "Houston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-26",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.CIV,
    teamB: TEAMS.ECU,
    status: "scheduled",
    datetime: "Jun 14, 2026 - 20:00",
    timestamp: 1781553600000,
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-27",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.GER,
    teamB: TEAMS.CIV,
    status: "scheduled",
    datetime: "Jun 20, 2026 - 17:00",
    timestamp: 1782061200000,
    stadium: "BMO Field",
    city: "Toronto",
    broadcasts: [RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-28",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.ECU,
    teamB: TEAMS.CUW,
    status: "scheduled",
    datetime: "Jun 20, 2026 - 21:00",
    timestamp: 1782075600000,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-29",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.ECU,
    teamB: TEAMS.GER,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 17:00",
    timestamp: 1782493200000,
    stadium: "MetLife Stadium",
    city: "New York/New Jersey",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-30",
    stage: "Group",
    group: "Group E",
    teamA: TEAMS.CUW,
    teamB: TEAMS.CIV,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 17:00",
    timestamp: 1782493200000,
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO F ---
  {
    id: "gm-31",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.NED,
    teamB: TEAMS.JPN,
    status: "scheduled",
    datetime: "Jun 14, 2026 - 17:00",
    timestamp: 1781542800000,
    stadium: "AT&T Stadium",
    city: "Dallas",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-32",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.SWE,
    teamB: TEAMS.TUN,
    status: "scheduled",
    datetime: "Jun 14, 2026 - 23:00",
    timestamp: 1781564400000,
    stadium: "Estádio BBVA",
    city: "Monterrey",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-33",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.NED,
    teamB: TEAMS.SWE,
    status: "scheduled",
    datetime: "Jun 20, 2026 - 14:00",
    timestamp: 1782050400000,
    stadium: "NRG Stadium",
    city: "Houston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-34",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.TUN,
    teamB: TEAMS.JPN,
    status: "scheduled",
    datetime: "Jun 21, 2026 - 01:00",
    timestamp: 1782090000000,
    stadium: "Estádio BBVA",
    city: "Monterrey",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-35",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.TUN,
    teamB: TEAMS.NED,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 20:00",
    timestamp: 1782504000000,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-36",
    stage: "Group",
    group: "Group F",
    teamA: TEAMS.JPN,
    teamB: TEAMS.SWE,
    status: "scheduled",
    datetime: "Jun 25, 2026 - 20:00",
    timestamp: 1782504000000,
    stadium: "AT&T Stadium",
    city: "Dallas",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO G ---
  {
    id: "gm-37",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.BEL,
    teamB: TEAMS.EGY,
    status: "scheduled",
    datetime: "Jun 15, 2026 - 16:00",
    timestamp: 1781625600000,
    stadium: "Lumen Field",
    city: "Seattle",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-38",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.IRN,
    teamB: TEAMS.NZL,
    status: "scheduled",
    datetime: "Jun 15, 2026 - 22:00",
    timestamp: 1781647200000,
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-39",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.BEL,
    teamB: TEAMS.IRN,
    status: "scheduled",
    datetime: "Jun 21, 2026 - 16:00",
    timestamp: 1782144000000,
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-40",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.NZL,
    teamB: TEAMS.EGY,
    status: "scheduled",
    datetime: "Jun 21, 2026 - 22:00",
    timestamp: 1782165600000,
    stadium: "BC Place",
    city: "Vancouver",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-41",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.EGY,
    teamB: TEAMS.IRN,
    status: "scheduled",
    datetime: "Jun 26, 2026 - 00:00",
    timestamp: 1782518400000,
    stadium: "Lumen Field",
    city: "Seattle",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-42",
    stage: "Group",
    group: "Group G",
    teamA: TEAMS.NZL,
    teamB: TEAMS.BEL,
    status: "scheduled",
    datetime: "Jun 26, 2026 - 00:00",
    timestamp: 1782518400000,
    stadium: "BC Place",
    city: "Vancouver",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO H ---
  {
    id: "gm-43",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.ESP,
    teamB: TEAMS.CPV,
    status: "scheduled",
    datetime: "Jun 15, 2026 - 13:00",
    timestamp: 1781614800000,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-44",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.KSA,
    teamB: TEAMS.URU,
    status: "scheduled",
    datetime: "Jun 15, 2026 - 19:00",
    timestamp: 1781636400000,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    broadcasts: [RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-45",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.ESP,
    teamB: TEAMS.KSA,
    status: "scheduled",
    datetime: "Jun 21, 2026 - 13:00",
    timestamp: 1782133200000,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-46",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.URU,
    teamB: TEAMS.CPV,
    status: "scheduled",
    datetime: "Jun 21, 2026 - 19:00",
    timestamp: 1782154800000,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-47",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.URU,
    teamB: TEAMS.ESP,
    status: "scheduled",
    datetime: "Jun 26, 2026 - 21:00",
    timestamp: 1782594000000,
    stadium: "Estádio Akron",
    city: "Guadalajara",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[1]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-48",
    stage: "Group",
    group: "Group H",
    teamA: TEAMS.CPV,
    teamB: TEAMS.KSA,
    status: "scheduled",
    datetime: "Jun 26, 2026 - 21:00",
    timestamp: 1782594000000,
    stadium: "NRG Stadium",
    city: "Houston",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO I ---
  {
    id: "gm-49",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.FRA,
    teamB: TEAMS.SEN,
    status: "scheduled",
    datetime: "Jun 16, 2026 - 16:00",
    timestamp: 1781712000000,
    stadium: "MetLife Stadium",
    city: "New York/New Jersey",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-50",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.REP2, // Mapped Iraque to REP2
    teamB: TEAMS.NOR,
    status: "scheduled",
    datetime: "Jun 16, 2026 - 19:00",
    timestamp: 1781722800000,
    stadium: "Gillette Stadium",
    city: "Boston",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-51",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.FRA,
    teamB: TEAMS.REP2, // Mapped Iraque to REP2
    status: "scheduled",
    datetime: "Jun 22, 2026 - 18:00",
    timestamp: 1782237600000,
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-52",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.NOR,
    teamB: TEAMS.SEN,
    status: "scheduled",
    datetime: "Jun 22, 2026 - 21:00",
    timestamp: 1782248400000,
    stadium: "MetLife Stadium",
    city: "New York/New Jersey",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-53",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.NOR,
    teamB: TEAMS.FRA,
    status: "scheduled",
    datetime: "Jun 26, 2026 - 16:00",
    timestamp: 1782576000000,
    stadium: "Gillette Stadium",
    city: "Boston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-54",
    stage: "Group",
    group: "Group I",
    teamA: TEAMS.SEN,
    teamB: TEAMS.REP2, // Mapped Iraque to REP2
    status: "scheduled",
    datetime: "Jun 26, 2026 - 16:00",
    timestamp: 1782576000000,
    stadium: "BMO Field",
    city: "Toronto",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO J ---
  {
    id: "gm-55",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.ARG,
    teamB: TEAMS.ALG,
    status: "scheduled",
    datetime: "Jun 16, 2026 - 22:00",
    timestamp: 1781733600000,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-56",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.AUT,
    teamB: TEAMS.JOR,
    status: "scheduled",
    datetime: "Jun 17, 2026 - 01:00",
    timestamp: 1781744400000,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-57",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.ARG,
    teamB: TEAMS.AUT,
    status: "scheduled",
    datetime: "Jun 22, 2026 - 14:00",
    timestamp: 1782223200000,
    stadium: "AT&T Stadium",
    city: "Dallas",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[1]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-58",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.JOR,
    teamB: TEAMS.ALG,
    status: "scheduled",
    datetime: "Jun 23, 2026 - 00:00",
    timestamp: 1782259200000,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-59",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.JOR,
    teamB: TEAMS.ARG,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 23:00",
    timestamp: 1782687600000,
    stadium: "AT&T Stadium",
    city: "Dallas",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-60",
    stage: "Group",
    group: "Group J",
    teamA: TEAMS.ALG,
    teamB: TEAMS.AUT,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 23:00",
    timestamp: 1782687600000,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO K ---
  {
    id: "gm-61",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.POR,
    teamB: TEAMS.COD, // Mapped Congo to COD
    status: "scheduled",
    datetime: "Jun 17, 2026 - 14:00",
    timestamp: 1781791200000,
    stadium: "NRG Stadium",
    city: "Houston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-62",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.UZB,
    teamB: TEAMS.COL,
    status: "scheduled",
    datetime: "Jun 17, 2026 - 23:00",
    timestamp: 1781823600000,
    stadium: "Estádio Azteca",
    city: "Mexico City",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-63",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.POR,
    teamB: TEAMS.UZB,
    status: "scheduled",
    datetime: "Jun 23, 2026 - 14:00",
    timestamp: 1782309600000,
    stadium: "NRG Stadium",
    city: "Houston",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-64",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.COL,
    teamB: TEAMS.COD, // Mapped Congo to COD
    status: "scheduled",
    datetime: "Jun 23, 2026 - 23:00",
    timestamp: 1782342000000,
    stadium: "Estádio Akron",
    city: "Guadalajara",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-65",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.COL,
    teamB: TEAMS.POR,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 20:30",
    timestamp: 1782678600000,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-66",
    stage: "Group",
    group: "Group K",
    teamA: TEAMS.COD, // Mapped Congo to COD
    teamB: TEAMS.UZB,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 20:30",
    timestamp: 1782678600000,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },

  // --- GRUPO L ---
  {
    id: "gm-67",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.ENG,
    teamB: TEAMS.CRO,
    status: "scheduled",
    datetime: "Jun 17, 2026 - 17:00",
    timestamp: 1781802000000,
    stadium: "AT&T Stadium",
    city: "Dallas",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-68",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.GHA,
    teamB: TEAMS.PAN,
    status: "scheduled",
    datetime: "Jun 17, 2026 - 20:00",
    timestamp: 1781812800000,
    stadium: "BMO Field",
    city: "Toronto",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-69",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.ENG,
    teamB: TEAMS.GHA,
    status: "scheduled",
    datetime: "Jun 23, 2026 - 17:00",
    timestamp: 1782320400000,
    stadium: "Gillette Stadium",
    city: "Boston",
    broadcasts: [RECENT_BROADCASTS[0], RECENT_BROADCASTS[3]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-70",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.PAN,
    teamB: TEAMS.CRO,
    status: "scheduled",
    datetime: "Jun 23, 2026 - 20:00",
    timestamp: 1782331200000,
    stadium: "BMO Field",
    city: "Toronto",
    broadcasts: [RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-71",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.PAN,
    teamB: TEAMS.ENG,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 18:00",
    timestamp: 1782669600000,
    stadium: "MetLife Stadium",
    city: "New York/New Jersey",
    broadcasts: [RECENT_BROADCASTS[1], RECENT_BROADCASTS[4]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
  {
    id: "gm-72",
    stage: "Group",
    group: "Group L",
    teamA: TEAMS.CRO,
    teamB: TEAMS.GHA,
    status: "scheduled",
    datetime: "Jun 27, 2026 - 18:00",
    timestamp: 1782669600000,
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    broadcasts: [RECENT_BROADCASTS[2]],
    timeline: [],
    stats: {
      possessionA: 0,
      possessionB: 0,
      shotsA: 0,
      shotsB: 0,
      shotsOnTargetA: 0,
      shotsOnTargetB: 0,
      foulsA: 0,
      foulsB: 0,
      cornersA: 0,
      cornersB: 0,
    },
  },
];

// Special dynamic broadcaster rule:
// CazéTV in all matches.
// Grupo Globo, SBT and N Sports in all matches involving Brazil.
const CAZE_TV_BROADCAST: BroadcastChannel = {
  id: "caze_tv",
  name: "CazéTV",
  type: "streaming",
  logoColor: "#FF6F00",
  urlPlaceholder: "https://www.youtube.com/@CazeTV",
};

const GLOBO_BROADCAST: BroadcastChannel = {
  id: "grupo_globo",
  name: "Grupo Globo",
  type: "free",
  logoColor: "#0054F0",
  urlPlaceholder: "https://globoplay.globo.com",
};

const SBT_BROADCAST: BroadcastChannel = {
  id: "sbt",
  name: "SBT",
  type: "free",
  logoColor: "#5B21B6",
  urlPlaceholder: "https://www.sbt.com.br",
};

const NSPORTS_BROADCAST: BroadcastChannel = {
  id: "nsports",
  name: "N Sports",
  type: "streaming",
  logoColor: "#10B981",
  urlPlaceholder: "https://www.nsports.com.br",
};

const applyBroadcasterRules = (matches: Match[]) => {
  matches.forEach((match) => {
    const isBrazilMatch = match.teamA.id === "BRA" || match.teamB.id === "BRA";

    // We want CazéTV on all matches.
    const targets = [CAZE_TV_BROADCAST];

    // For Brazil matches, add Grupo Globo, SBT, and N Sports.
    if (isBrazilMatch) {
      targets.push(GLOBO_BROADCAST, SBT_BROADCAST, NSPORTS_BROADCAST);
    }

    // Merge into the match's broadcasts, avoiding duplicate IDs or names (and filter TV Globo if Grupo Globo is added)
    let current = [...match.broadcasts];
    if (isBrazilMatch) {
      current = current.filter(
        (c) =>
          c.name !== "TV Globo" &&
          c.id !== "grupo_globo" &&
          c.id !== "sbt" &&
          c.id !== "nsports" &&
          c.id !== "caze_tv",
      );
    } else {
      current = current.filter((c) => c.id !== "caze_tv");
    }

    targets.forEach((tgt) => {
      if (
        !current.some(
          (c) =>
            c.id === tgt.id || c.name.toLowerCase() === tgt.name.toLowerCase(),
        )
      ) {
        current.push(tgt);
      }
    });

    match.broadcasts = current;
  });
};

applyBroadcasterRules(BRACKET_MATCHES);
applyBroadcasterRules(GROUP_MATCHES);
